runtime: go113

env_variables:
  WWFListen: $PORT
  WWFKey: TheRightToCommunicateFreelyPrivatelySecretlyAndSecurelyIsEssentialForASafeSociety
  WWFLogging: No
  WWFIdleTimeout: 120
  WWFDialTimeout: 5
  WWFRetrieveTimeout: 3
  WWFMaxOutgoingConnections: 128

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: automatic
  min_idle_instances: 0

handlers:
  - url: /.*
    script: auto
    secure: always
